export const userRights = {
  ROLE_MANAGE_USER: 'ROLE_MANAGE_USER',
  ROLE_MANAGE_PRODUCT: 'ROLE_MANAGE_PRODUCT',
  ROLE_MANAGE_PROFILE: 'ROLE_MANAGE_PROFILE',
  ROLE_MANAGE_SUBSCRIBER: 'ROLE_MANAGE_SUBSCRIBER',
  ROLE_MANAGE_REPORTS: 'ROLE_MANAGE_REPORTS',
};
