export const data = [
  {
    no: 1,
    batchName: 'Batch A',
    timing: '10:00 AM - 12:00 PM',
    schedule: 'Mon, Wed, Fri',
    trainer: 'John Doe',
    duration: '3 months',
    candidates: 25,
    cost: '$300',
    status: 'Active',
  },
  {
    no: 2,
    batchName: 'Batch B',
    timing: '2:00 PM - 4:00 PM',
    schedule: 'Tue, Thu, Sat',
    trainer: 'Jane Smith',
    duration: '2 months',
    candidates: 18,
    cost: '$250',
    status: 'Inactive',
  },
  {
    no: 3,
    batchName: 'Batch C',
    timing: '6:00 PM - 8:00 PM',
    schedule: 'Mon, Wed, Fri',
    trainer: 'Emily Clark',
    duration: '4 months',
    candidates: 30,
    cost: '$350',
    status: 'Active',
  },
  {
    no: 4,
    batchName: 'Batch D',
    timing: '8:00 AM - 10:00 AM',
    schedule: 'Tue, Thu',
    trainer: 'Michael Lee',
    duration: '5 months',
    candidates: 20,
    cost: '$400',
    status: 'Active',
  },
  {
    no: 5,
    batchName: 'Batch E',
    timing: '12:00 PM - 2:00 PM',
    schedule: 'Mon, Wed, Fri',
    trainer: 'Chris Wilson',
    duration: '6 months',
    candidates: 15,
    cost: '$500',
    status: 'Inactive',
  },
  {
    no: 6,
    batchName: 'Batch F',
    timing: '4:00 PM - 6:00 PM',
    schedule: 'Sat, Sun',
    trainer: 'Sarah Johnson',
    duration: '3 months',
    candidates: 22,
    cost: '$280',
    status: 'Active',
  },
];
