export const data = [
  {
    no: 1,
    profile: 1,
    name: 'Batch A',
    subscriptionIn: '10:00 AM - 12:00 PM',
    batch: 'Mon, Wed, Fri',
    username: 'John Doe',
    date: '3 months',
    cost: '$300',
    status: 'Active',
  },
  {
    no: 2,
    profile: 2,
    name: 'Batch B',
    subscriptionIn: '2:00 PM - 4:00 PM',
    batch: 'Tue, Thu, Sat',
    username: 'Jane Smith',
    date: '2 months',
    cost: '$250',
    status: 'Inactive',
  },
  {
    no: 3,
    profile: 3,
    name: 'Batch C',
    subscriptionIn: '6:00 PM - 8:00 PM',
    batch: 'Mon, Wed, Fri',
    username: 'Emily Clark',
    date: '4 months',
    cost: '$350',
    status: 'Active',
  },
  {
    no: 4,
    profile: 4,
    name: 'Batch D',
    subscriptionIn: '8:00 AM - 10:00 AM',
    batch: 'Tue, Thu',
    username: 'Michael Lee',
    date: '5 months',
    cost: '$400',
    status: 'Active',
  },
  {
    no: 5,
    profile: 5,
    name: 'Batch E',
    subscriptionIn: '12:00 PM - 2:00 PM',
    batch: 'Mon, Wed, Fri',
    username: 'Chris Wilson',
    date: '6 months',
    cost: '$500',
    status: 'Inactive',
  },
  {
    no: 6,
    profile: 6,
    name: 'Batch F',
    subscriptionIn: '4:00 PM - 6:00 PM',
    batch: 'Sat, Sun',
    username: 'Sarah Johnson',
    date: '3 months',
    cost: '$280',
    status: 'Active',
  },
];

export const customerData = [
  {
    icon: 'icon1.svg',
    name: 'John Doe',
    email: 'john.doe@example.com',
    priceRange: '$100 - $200',
    service: 'Cricket',
    batch: 'Morning Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    icon: 'icon2.svg',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    priceRange: '$150 - $250',
    service: 'Football',
    batch: 'Morning Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    icon: 'icon3.svg',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    priceRange: '$200 - $300',
    service: 'Baseball',
    batch: 'Evening Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    icon: 'icon3.svg',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    priceRange: '$200 - $300',
    service: 'Baseball',
    batch: 'Evening Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    icon: 'icon3.svg',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    priceRange: '$200 - $300',
    service: 'Baseball',
    batch: 'Evening Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },

  {
    icon: 'icon3.svg',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    priceRange: '$200 - $300',
    service: 'Baseball',
    batch: 'Evening Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    icon: 'icon3.svg',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    priceRange: '$200 - $300',
    service: 'Baseball',
    batch: 'Evening Batch',
    expiretime: '13hrs',
    description:
      'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  // Add more customer objects as needed
];

export const subscriptionData = [
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'cricket',
    batch: 'Evening',
    username: '@Zafar',
    expriyStatus: '13hrs',
  },

  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'football',
    batch: 'Morning',
    username: '@khan',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
  {
    no: '#1234',
    name: 'Alice Johnson',
    profile: 'alice.johnson@example.com',
    subscriptionIn: 'baseball',
    batch: 'Morning',
    username: '@Imran',
    expriyStatus: '13hrs',
  },
];
