export const data = [
  {
    no: 1,
    profile: 1,
    name: 'Batch A',
    subscriptionIn: '10:00 AM - 12:00 PM',
    batch: 'Mon, Wed, Fri',
    username: 'John Doe',
    date: '3 months',
    cost: '$300',
    status: 'Active',
  },
  {
    no: 2,
    profile: 2,
    name: 'Batch B',
    subscriptionIn: '2:00 PM - 4:00 PM',
    batch: 'Tue, Thu, Sat',
    username: 'Jane Smith',
    date: '2 months',
    cost: '$250',
    status: 'Inactive',
  },
  {
    no: 3,
    profile: 3,
    name: 'Batch C',
    subscriptionIn: '6:00 PM - 8:00 PM',
    batch: 'Mon, Wed, Fri',
    username: 'Emily Clark',
    date: '4 months',
    cost: '$350',
    status: 'Active',
  },
  {
    no: 4,
    profile: 4,
    name: 'Batch D',
    subscriptionIn: '8:00 AM - 10:00 AM',
    batch: 'Tue, Thu',
    username: 'Michael Lee',
    date: '5 months',
    cost: '$400',
    status: 'Active',
  },
  {
    no: 5,
    profile: 5,
    name: 'Batch E',
    subscriptionIn: '12:00 PM - 2:00 PM',
    batch: 'Mon, Wed, Fri',
    username: 'Chris Wilson',
    date: '6 months',
    cost: '$500',
    status: 'Inactive',
  },
  {
    no: 6,
    profile: 6,
    name: 'Batch F',
    subscriptionIn: '4:00 PM - 6:00 PM',
    batch: 'Sat, Sun',
    username: 'Sarah Johnson',
    date: '3 months',
    cost: '$280',
    status: 'Active',
  },
];

export const customerData = [
  {
    name: 'Kevin Bathgate',
    username: 'kbathgate',
    originalPrice: 149,
    finalPrice: 115,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '13hrs',
    message: 'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    name: 'Emily Blunt',
    username: 'emilyblunt',
    originalPrice: 149,
    finalPrice: 130,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '12hrs',
    message: "Hello Coach, I'm eager to sign my child up for your basketball program. However, I was hoping you might consider offering a discount or a reduced rate. It would make a big difference for us, and we'd love to join. Thanks!",
    status: 'Approved',
    statusDate: '47 Days ago',
    avatar: '/path/to/emily-avatar.jpg'
  },
  {
    name: 'Rosie Fuller',
    username: 'rosief',
    originalPrice: 149,
    counterPrice: 100,
    finalPrice: 125,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '11hrs',
    message: 'Heard you are the best in town. My kids want to join the current program but we are kind of short in budget. Can you help us out on offering some sort of discount that will enable my kid to join? Appreciated.',
    status: 'Counter Offer',
    statusDate: '(Accepted by Customer) 47 Days ago',
  },
  {
    name: 'Sue Yuh',
    username: 'Suerock',
    originalPrice: 50,
    finalPrice: 15,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '10hrs',
    message: "Hi Coach, I'm excited to enroll my child in your basketball program. Would you consider offering a discount or reduced fee? It would be a huge help, and we're really looking forward to being part of the team. Thank you!",
    status: 'Rejected',
    statusDate: '47 Days ago',
    avatar: '/path/to/sue-avatar.jpg'
  },
  {
    name: 'Kevin Bathgate',
    username: 'kbathgate',
    originalPrice: 149,
    finalPrice: 115,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '13hrs',
    message: 'My child is interested to join the upcoming batch and it is convenient for us to drop the kid due to close proximity. Would appreciate if you could consider reserving a seat for my child at the price I had proposed. Looking forward to enroll.',
  },
  {
    name: 'Emily Blunt',
    username: 'emilyblunt',
    originalPrice: 149,
    finalPrice: 130,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '12hrs',
    message: "Hello Coach, I'm eager to sign my child up for your basketball program. However, I was hoping you might consider offering a discount or a reduced rate. It would make a big difference for us, and we'd love to join. Thanks!",
    status: 'Approved',
    statusDate: '47 Days ago',
    avatar: '/path/to/emily-avatar.jpg'
  },
  {
    name: 'Rosie Fuller',
    username: 'rosief',
    originalPrice: 149,
    counterPrice: 100,
    finalPrice: 125,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '11hrs',
    message: 'Heard you are the best in town. My kids want to join the current program but we are kind of short in budget. Can you help us out on offering some sort of discount that will enable my kid to join? Appreciated.',
    status: 'Counter Offer',
    statusDate: '(Accepted by Customer) 47 Days ago',
  },
  {
    name: 'Sue Yuh',
    username: 'Suerock',
    originalPrice: 50,
    finalPrice: 15,
    sport: 'Baseball',
    batchType: 'Morning Batch',
    timeToExpire: '10hrs',
    message: "Hi Coach, I'm excited to enroll my child in your basketball program. Would you consider offering a discount or reduced fee? It would be a huge help, and we're really looking forward to being part of the team. Thank you!",
    status: 'Rejected',
    statusDate: '47 Days ago',
    avatar: '/path/to/sue-avatar.jpg'
  }
  // Add more customer objects as needed
];

export const subscriptionData = [
  {
    id: 2534,
    no: '#2534',
    profile: 'JM',
    name: 'Joan Marquardt',
    subscriptionIn: 'Baseball',
    batch: 'Morning Training',
    username: '@jmarquardnt',
    expriyStatus: '1 day left',
    action: 'Email Reminder'
  },
  {
    id: 2533,
    no: '#2533',
    profile: 'SH',
    name: 'Sarah Howe MD',
    subscriptionIn: 'Basketball',
    batch: 'Evening Training',
    username: '@showe',
    expriyStatus: '3 days left',
    action: 'Email Reminder'
  },
  {
    id: 2532,
    no: '#2532',
    profile: 'SZ',
    name: 'Santiago Ziemann',
    subscriptionIn: 'Baseball',
    batch: 'Morning Training',
    username: '@sziemann',
    expriyStatus: '4 days left',
    action: 'Email Reminder'
  },
  {
    id: 2531,
    no: '#2531',
    profile: 'MD',
    name: 'Mary Dare',
    subscriptionIn: 'Basketball',
    batch: 'Evening Training',
    username: '@marydare',
    expriyStatus: 'Expired 2 day ago',
    action: 'Email Reminder'
  },
  {
    id: 2530,
    no: '#2530',
    profile: 'CM',
    name: 'Carol Murazik',
    subscriptionIn: 'Baseball',
    batch: 'Morning Training',
    username: '@carlosm',
    expriyStatus: 'Expired 2 day ago',
    action: 'Email Sent'
  },
  {
    id: 2529,
    no: '#2529',
    profile: 'BK',
    name: 'Beth Kreiger',
    subscriptionIn: 'Basketball',
    batch: 'Evening Training',
    username: '@bkreiger',
    expriyStatus: 'Expired 2 day ago',
    action: 'Email Sent'
  }
];
