export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua & Deps',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Rep',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo {Democratic Rep}',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland {Republic}',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea North',
  'Korea South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar, {Burma}',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'St Kitts & Nevis',
  'St Lucia',
  'Saint Vincent & the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome & Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'Indianapolis',
  'Charlotte',
  'San Francisco',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'El Paso',
  'Detroit',
  'Nashville',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Mesa',
  'Kansas City',
  'Atlanta',
  'Miami',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'New Orleans',
  'Cleveland',
  'Honolulu',
  'Orlando',
  'Raleigh',
  'Richmond',
  'Salt Lake City',
  'St. Louis',
  'San Juan',
  'Pittsburgh',
  'Cincinnati',
  'Anchorage',
  'Birmingham',
  'Boise',
  'Des Moines',
  'Little Rock',
  'Madison',
  'Wichita',
  'Omaha',
  'Buffalo',
  'Fort Lauderdale',
  'Hartford',
  'Jackson',
  'Lansing',
  'Lincoln',
  'Springfield',
  'Tallahassee',
  'Topeka',
  'Montgomery',
  'Albany',
  'Providence',
  'Phoenix',
  'Tucson',
  'London',
  'Paris',
  'Berlin',
  'Rome',
  'Madrid',
  'Vienna',
  'Zurich',
  'Brussels',
  'Amsterdam',
  'Copenhagen',
  'Oslo',
  'Stockholm',
  'Moscow',
  'Helsinki',
  'Warsaw',
  'Prague',
  'Budapest',
  'Bucharest',
  'Lisbon',
  'Dublin',
  'Tokyo',
  'Seoul',
  'Beijing',
  'Shanghai',
  'Bangkok',
  'Manila',
  'Jakarta',
  'Kuala Lumpur',
  'Singapore',
  'Hanoi',
  'Mumbai',
  'New Delhi',
  'Bangalore',
  'Chennai',
  'Sydney',
  'Melbourne',
  'Brisbane',
  'Auckland',
  'Perth',
  'Adelaide',
  'Cairo',
  'Casablanca',
  'Johannesburg',
  'Lagos',
  'Nairobi',
  'Cape Town',
  'Accra',
  'Durban',
  'Kigali',
  'Addis Ababa',
  'Kampala',
  'Luanda',
  'Dar es Salaam',
];

export const getRelativeTime = timestamp => {
  // Ensure the timestamp is treated as milliseconds
  const date = new Date(timestamp);

  // Get the current date
  const now = new Date();

  // Calculate the difference in milliseconds
  const diffInMs = Math.abs(now - date);

  // Convert milliseconds to units
  const years = diffInMs / (365 * 24 * 60 * 60 * 1000);
  const months = (years % 1) * 12;
  const days = (months % 1) * 30; // Approximation: 30 days per month
  const hours = (days % 1) * 24;
  const minutes = (hours % 1) * 60;
  const seconds = (minutes % 1) * 60;

  // Floor values for formatting
  const [
    floorYears,
    floorMonths,
    floorDays,
    floorHours,
    floorMinutes,
    floorSeconds,
  ] = [
    Math.floor(years),
    Math.floor(months),
    Math.floor(days),
    Math.floor(hours),
    Math.floor(minutes),
    Math.floor(seconds),
  ];

  // Format the result
  if (floorYears >= 5) {
    return `5+ years ago`;
  } else if (floorYears > 0) {
    return `${floorYears} year${floorYears > 1 ? 's' : ''} ago`;
  } else if (floorMonths > 0) {
    return `${floorMonths} month${floorMonths > 1 ? 's' : ''} ago`;
  } else if (floorDays > 0) {
    return `${floorDays} day${floorDays > 1 ? 's' : ''} ago`;
  } else if (floorHours > 0) {
    return `${floorHours} hour${floorHours > 1 ? 's' : ''} ago`;
  } else if (floorMinutes > 0) {
    return `${floorMinutes} minute${floorMinutes > 1 ? 's' : ''} ago`;
  } else {
    return `${floorSeconds} second${floorSeconds > 1 ? 's' : ''} ago`;
  }
};
